name: detect-create-package-manager

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: detect-create-package-manager-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: "latest"
          run_install: true
      - name: Build
        run: pnpm build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: "latest"
          run_install: true
      - name: Test
        run: pnpm test
